apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight
  template:
    metadata:
      labels:
        app: flight
    spec:
      containers:
      - name: flight
        image: flight:latest
        ports:
        - containerPort: 5004
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"