apiVersion: apps/v1
kind: Deployment
metadata:
  name: reserves-payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reserves-payment
  template:
    metadata:
      labels:
        app: reserves-payment
    spec:
      containers:
      - name: reserves-payment
        image: reserves-payment:latest
        ports:
        - containerPort: 5004
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"